# Generated by Django 5.2 on 2025-04-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('marital_status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('husband_wife_name', models.CharField(blank=True, max_length=100)),
                ('native', models.CharField(max_length=100)),
                ('current_resident', models.CharField(blank=True, max_length=100)),
                ('baptism_details', models.CharField(default='No', max_length=3)),
                ('contact_number', models.CharField(blank=True, max_length=15)),
            ],
        ),
    ]
