# Generated by Django 5.2 on 2025-05-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='date_of_birth',
            field=models.DateField(help_text='Select your date of birth', verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='husband_wife_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Husband/Wife Name'),
        ),
    ]
