# Generated by Django 5.2 on 2025-05-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_alter_userdetail_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='baptism_details',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='contact_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='current_resident',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Select your date of birth', verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='education',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='father_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='native',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
