# Generated by Django 5.2 on 2025-05-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_alter_userdetail_baptism_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Select your date of birth', null=True, verbose_name='Date of Birth'),
        ),
    ]
