# Generated by Django 5.2 on 2025-05-01 08:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_alter_userdetail_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetail',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Modified'),
        ),
    ]
